os: linux
dist: xenial
language: go
addons:
  apt:
    install: jq

script:
  - if [ -z ${TRAVIS_TAG} ] || [[ ${TRAVIS_TAG} == *-* ]]; then export VERSION=latest;
    else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}
  - date > out.txt
  - echo ${VERSION} >> out.txt

before_deploy:
  - if [[ ${VERSION} == "latest" ]]; then export OLD_RELEASE_ID=`curl -u amreo:$GITHUB_RELEASE_TOKEN https://api.github.com/repos/amreo/helloworld/releases/tags/master-latest | jq '.id'`; fi
  - if [[ ${VERSION} == "latest" ]]; then echo $OLD_RELEASE_ID; fi
  - if [[ ${VERSION} == "latest" ]]; then curl -X DELETE -u amreo:$GITHUB_RELEASE_TOKEN https://api.github.com/repos/amreo/helloworld/releases/$OLD_RELEASE_ID; fi || true

deploy:
  - provider: releases
    api_key: ${GITHUB_RELEASE_TOKEN}
    file: out.txt
    name: "master-latest"
    body: "master-latest"
    tag_name: master-latest
    prerelease: true
    overwrite: true
    skip_cleanup: true
    on:
      repo: amreo/helloworld
  - provider: releases
    api_key: ${GITHUB_RELEASE_TOKEN}      
    file: out.txt
    on:
      repo: amreo/helloworld
      tags: true
    skip_cleanup: true
 